# Generated by Django 5.2.5 on 2025-08-31 10:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('whatsapp_number', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('stokvel_tier', models.CharField(choices=[('Savings', 'Savings'), ('Investment', 'Investment'), ('Wealth', 'Wealth')], default='Savings', max_length=20)),
                ('stokvel_status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Exited', 'Exited')], default='Active', max_length=20)),
                ('kyc_status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('id_image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_auth_at', models.DateTimeField(auto_now=True)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('zu', 'Zulu'), ('xh', 'Xhosa'), ('af', 'Afrikaans')], default='en', max_length=2)),
                ('biometric_id', models.CharField(blank=True, max_length=255, null=True)),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
                ('total_savings', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_investment', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('stokfella_reference_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
